export const housesData = [
  {
    id: 1,
    image: "/housesImages/caxkadzor.png",
    night: true,
    people: "15",
    prace: "80,000Դ",
    title: "Ծաղկաձոր",
    sliderImages: [
      "/housesImages/caxkadzorS2.png",
      "/housesImages/caxkadzorS3.png",
    ],
  },
  {
    id: 2,
    image: "/housesImages/ohanavan.png",
    night: false,
    people: "25",
    prace: "90,000Դ",
    title: "Օհանավան",
    sliderImages: [
      "/housesImages/ohanavanS4.png",
      "/housesImages/ohanavanS7.png",
    ],
  },
  {
    id: 3,
    image: "/housesImages/erevan.png",
    night: true,
    people: "12",
    prace: "70,000Դ",
    title: "Երևան",
    sliderImages: ["/housesImages/erevanS1.png", "/housesImages/erevanS2.png"],
  },
  {
    id: 4,
    image: "/housesImages/dilijan.png",
    night: false,
    people: "20",
    prace: "85,000Դ",
    title: "Դիլիջան",
    sliderImages: [
      "/housesImages/dilijanS1.png",
      "/housesImages/dilijanS2.png",
    ],
  },
  {
    id: 5,
    image: "/housesImages/caxkadzor1.png",
    night: true,
    people: "18",
    prace: "95,000Դ",
    title: "Ծաղկաձոր",
    sliderImages: [
      "/housesImages/caxkadzorS4.png",
      "/housesImages/caxkadzorS5.png",
    ],
  },
  {
    id: 6,
    image: "/housesImages/draxtik.png",
    night: false,
    people: "30",
    prace: "100,000Դ",
    title: "Դրախտիկ",
    sliderImages: [
      "/housesImages/draxtikS1.png",
      "/housesImages/draxtikS2.png",
    ],
  },
  {
    id: 7,
    image: "/housesImages/garni.png",
    night: true,
    people: "22",
    prace: "110,000Դ",
    title: "Գառնի",
    sliderImages: ["/housesImages/garniS1.png", "/housesImages/garniS2.png"],
  },
  {
    id: 8,
    image: "/housesImages/ohanavan.png",
    night: false,
    people: "16",
    prace: "75,000Դ",
    title: "Օհանավան",
    sliderImages: [
      "/housesImages/ohanavanS3.png",
      "/housesImages/ohanavanS4.png",
    ],
  },
  {
    id: 9,
    image: "/housesImages/mrgashen.png",
    night: true,
    people: "14",
    prace: "70,000Դ",
    title: "Մրգաշեն",
    sliderImages: [
      "/housesImages/mrgashenS1.png",
      "/housesImages/mrgashenS2.png",
    ],
  },
  {
    id: 10,
    image: "/housesImages/hrazdan.png",
    night: false,
    people: "28",
    prace: "95,000Դ",
    title: "Հրազդան",
    sliderImages: [
      "/housesImages/hrazdanS1.png",
      "/housesImages/hrazdanS2.png",
    ],
  },
  {
    id: 11,
    image: "/housesImages/ohanavan1.png",
    night: true,
    people: "18",
    prace: "85,000Դ",
    title: "Օհանավան",
    sliderImages: [
      "/housesImages/ohanavanS5.png",
      "/housesImages/ohanavanS6.png",
    ],
  },
  {
    id: 12,
    image: "/housesImages/caxkadzor.png",
    night: false,
    people: "24",
    prace: "90,000Դ",
    title: "Ծաղկաձոր",
    sliderImages: [
      "/housesImages/caxkadzorS6.png",
      "/housesImages/caxkadzorS7.png",
    ],
  },
  {
    id: 13,
    image: "/housesImages/ohanavan2.png",
    night: true,
    people: "20",
    prace: "100,000Դ",
    title: "Օհանավան",
    sliderImages: [
      "/housesImages/ohanavanS7.png",
      "/housesImages/ohanavanS2.png",
    ],
  },
  {
    id: 14,
    image: "/housesImages/erevan.png",
    night: false,
    people: "26",
    prace: "105,000Դ",
    title: "Երևան",
    sliderImages: ["/housesImages/erevanS3.png", "/housesImages/erevanS2.png"],
  },
];
export const infoForServicesSpasarkum = [
  {
    title: "Մատուցող",
    image: "/servicesImages/sNkar1.png",
    prace: "20,000Դ",
    name: "Յուրաքանյչուր մատուցող կարող է սպասարկել 15-20 անձի։ Ծառայության արժեքը կախված է միջոցառման անցկացման վայրից։ Ձեր միջոցառման կազմակերպման գործում Ձեզ կօգնեն մեր փորձառու մատուցողները: Հաղորդակցման գերազանց հմտություններով և մանրուքների հանդեպ ուշադրությամբ, նրանք կապահովեն հյուրընկալ մթնոլորտ և բարձրակարգ սպասարկում։ Մեր հանգստյան գոտիներում անցկացրած միջոցառումները կթողնեն անմոռանալի հիշողություններ ի շնորհիվ մեր տարիների փորձի։",
  },
  {
    title: "Բարմեն",
    image: "/servicesImages/sNkar2.png",
    prace: "25,000Դ",
    name: "Մեր պրոֆեսիոնալ բարմենները տիրապետում են տարբեր տեսակի խմիչքների պատրաստման հմտություններին։ Մեր բարմենները պատասխանատու են բարում նստած հաճախորդներին բարձրակարգ սպասարկում մատուցելու համար, ինչպես նաև հյուրերին խմիչքների ընտրության հարցում խորհրդատվություն տրամադրելու, հաճախորդների պահանջներին արձագանքելու համար։",
  },
  {
    title: "Խոհարար",
    image: "/servicesImages/sNkar3.png",
    prace: "35,000Դ",
    name: "Արժեքը կախված է միջոցառման անձանց քանակից և ուտեստների մենյուից։ Ունենալով հարուստ փորձ և տաղանդ, Մեր խոհարարները ստեղծում են համերի և նրբաճաշակության զարմանալի համադրություններ: Մեր խոհարարները ընտրում են միայն ամենաթարմ և ամենաբարձր որակի բաղադրիչները, որպեսզի Ձեզ մատուցեն յուրահատուկ խոհարարական փորձ: Մեր խոհարարները պատասխանատու են սննդի պատրաստման և պատրաստման տեխնիկայ։համար: Նրանք ապահովում են ցանկացած տեսակի սննդի պատրաստումը՝ նախնական համաձայնության գալով միջոցառման կազմակերպչի հետ։",
  },
  {
    title: "Հանդիսավար",
    image: "/servicesImages/sNkar4.png",
    prace: "260,000Դ",
    name: "Այս բաժնում մենք կփորձենք օգնել Ձեզ հանդիսավարի (թամադայի), ընտրության հարցում, քանի որ միայն իսկական հանդիսավարը կարող է իր վարպետությամբ ստեղծել հիասքանչ և տոնական մթնոլորտ։",
  },
  {
    title: "Փրփուր Փարթի",
    image: "/servicesImages/sNkar5.png",
    prace: "26,900Դ",
    name: "Նյութերը սերտիֆիկացված են, աչքերը չեն մռմռացնում, ալերգիա չեն առաջացնում, անվնաս են նաև բույսերի և լողավազանի համար:",
  },
];
export const infoForServicesShou = [
  {
    title: "Դի-Ջեյ",
    image: "/servicesImages/shNkar1.png",
    prace: "50,000Դ",
    name: "Դիջեյներն Մեր կազմակերպած միջոցառումների աստղերն են՝ ովքեր ստեղծում են յուրահատուկ մթնոլորտ և զվարճանք: Amaranoc.am-ի դիջեյները վարպետորեն տիրապետում են երաժշտական ​​ռեպերտուարին, որը կարող է գոհացնել յուրաքանչյուր ճաշակ և բարձրացնել տրամադրություն: Իրենց երաժշտական ​​միքսերով նրանք երեկոն վերածում են իրական խնջույքի,որը դեռ երկար կմնա մեր հյուրերի հիշողության մեջ։",
  },
  {
    title: "Երգիչ",
    prace: "150,000Դ",
    image: "/servicesImages/shNkar2.png",
    name: "Amaranoc.am ի երգիչները, իրենց զարմանալի ձայնով և տաղանդով, կստեղծեն յուրահատուկ մթնոլորտ։ Ընկղմվեք հնչյունների և ռիթմերի աշխարհում՝ վայելելով երաժշտության աննկարագրելի հաճույքը։",
  },
  {
    title: "Կրակներով շոու",
    prace: "50,000Դ",
    image: "/servicesImages/shNkar3.png",
    name: "Կրակներով շոուն կստեղծի վառ և հիասքանչ ժամանց, որոնք կտպավորվեն մշտեպես Ձեր հիշողության մեջ։ Մեր պրոֆեսիոնալ արտիստները տիրապետելով կրակի հետ խաղալու արվեստին, ստեղծում են ապշեցուցիչ գեղեցկությամբ և ադրենալինով լի ներկայացումներ: Այստեղ դուք կընկղմվեք մի աշխարհ,որտեղ դուք ամբողջովին կզգաք կրակի իրական գեղեցկությունը և ջերմությունը։",
  },
  {
    title: "Ջութակահար",
    prace: "80,000Դ",
    image: "/servicesImages/shNkar4.png",
    name: "Մեր տաղանդավոր երաժիշտները կստեղծեն անկրկնելի մթնոլորտ, որը կլցնի Ձեր միջոցառումը երաժշտության հրաշքներով՝ դասական հնչյուններից մինչև ժամանակակից հիթեր։ Մեղեդիների ուղեկցությամբ Դուք կտեղափոխվեք մի աշխարհ՝ լցված նրբագեղությամբ և ոգեշնչմամբ։",
  },
  {
    title: "Խաղավար",
    prace: "15,000Դ",
    image: "/servicesImages/shNkar5.png",
    name: "Մեր խաղավարները միշտ կգտնեն Ձեր հյուրերին ուրախացնելու և Ձեր միջոցառումը մրցույթներով զարդարելու միջոց:",
  },
  {
    title: "Մուլտհերոսներ",
    prace: "5,000Դ",
    image: "/servicesImages/shNkar6.png",
    name: "Մեր մուլտհերոսները կախարդական կերպարներ են, ովքեր ժպիտ ու ուրախություն կպարգևեն ոչ միայն երեխաներին, այլև մեծերին: Իրենց գունեղ անհատականություններով նրանք ձեզ կտանեն ֆանտաստիկայի և արկածների հիանալի աշխարհ՝ բարի և խիզախ սուպերհերոսներից մինչև սրամիտ և զվարճալի կենդանիներ։ Ձեր միջոցառմանը հրավիրեք Մեր սիրելի մուլտհերոսներին, և նրանք կպարգևեն Ձեր հյուրերին ուրախության և կախարդական նմոռանալի պահեր:",
  },
];
export const infoForServicesMijocarumner = [
  {
    title: "Նշանադրության կազմակերպում",
    prace: "500,000Դ",
    image: "/servicesImages/mNkar1.png",
    name: "Նշանադրության արարողությունը առանձնահատուկ պահ է զույգի կյանքում: Մեր ընկերությունը կազմակերպում է նշանադրության արարողություն, որը ստեղծում է կախարդական պահեր սիրահարների համար: Մեր նպատակն է անմոռանալի դարձնել այդ հիասքանչ միջոցառումը։ Մենք ցուցաբերում ենք անհատական մոտեցում յուրաքանչյուր զույգին՝ օգնելով նրանց ստեղծել կատարյալ իրադարձություն։ Մեր փորձառու և ստեղծագործ թիմը կապահովի արարողության գեղեցիկ դիզայնը ,սպասարկումը, երաժշտությունը,լուսային էֆֆեկտները և բոլոր մանրուքները, ինչը կօգնի լիարժեք վայելելու Ձեր օրը։",
  },
  {
    title: "Ծննդյան առիթների կազմակերպում",
    prace: "150,000Դ",
    image: "/servicesImages/mNkar2.png",
    name: "«Amaranoc.am»-ը ձեր վստահելի գործընկերն է ծննդյան տոների կազմակերպման գործում: Մենք մասնագիտացած ենք ստեղծելու անմոռանալի միջոցառումներ, որոնք ընդգծում են հոբելյարի յուրահատկությունն ու անհատականությունը: Մեր կրեատիվ մասնագետների թիմը հոգ կտանի ամեն ինչի մասին՝ սկսած կոնցեպտից և դեկորից, մինչև զվարճանք և խոհարարական հյուրասիրություն: Վստահե՛ք մեզ ձեր ծննդյան օրը կազմակերպելու գործը, և այն իսկապես անմոռանալի կլինի:",
  },
  {
    title: "Հարսանյաց սենյակի ձևավորում",
    prace: "80,000Դ",
    image: "/servicesImages/mNkar3.png",
    name: "Հարսանյաց սենյակի ձևավորման գործում Ձեզ կօգնի Մեր դիզայներների և ոճաբանների թիմը՝ ովքեր հաշվի առնելով Ձեր նախասիրությունները և անհատականությունը, կհաղորդեն սենյակին նրբաճաշակություն, շքեղություն: Նուրբ գործվածքներից և մոմերից մինչև նրբաճաշակ ծաղիկներ և զարդեր։ ️️Վստահեք Ձեր կյանքի ամենակարևոր առիթներից մեկը Մեր թիմին, ունենալով շքեղ և չկրկնվող ձևավորումներ։",
  },
];
