export const housesData = [
  {
    id: 1,
    image: "housesImages/caxkadzor.png",
    night: true,
    people: "15",
    prace: "80,000Դ",
    title: "Ծաղկաձոր",
    sliderImages: [
      "housesImages/caxkadzorS2.png",
      "housesImages/caxkadzorS3.png",
    ],
  },
  {
    id: 2,
    image: "housesImages/ohanavan.png",
    night: false,
    people: "25",
    prace: "90,000Դ",
    title: "Օհանավան",
    sliderImages: [
      "housesImages/ohanavanS4.png",
      "housesImages/ohanavanS7.png",
    ],
  },
  {
    id: 3,
    image: "housesImages/erevan.png",
    night: true,
    people: "12",
    prace: "70,000Դ",
    title: "Երևան",
    sliderImages: ["housesImages/erevanS1.png", "housesImages/erevanS2.png"],
  },
  {
    id: 4,
    image: "housesImages/dilijan.png",
    night: false,
    people: "20",
    prace: "85,000Դ",
    title: "Դիլիջան",
    sliderImages: ["housesImages/dilijanS1.png", "housesImages/dilijanS2.png"],
  },
  {
    id: 5,
    image: "housesImages/caxkadzor1.png",
    night: true,
    people: "18",
    prace: "95,000Դ",
    title: "Ծաղկաձոր",
    sliderImages: [
      "housesImages/caxkadzorS4.png",
      "housesImages/caxkadzorS5.png",
    ],
  },
  {
    id: 6,
    image: "housesImages/draxtik.png",
    night: false,
    people: "30",
    prace: "100,000Դ",
    title: "Դրախտիկ",
    sliderImages: ["housesImages/draxtikS1.png", "housesImages/draxtikS2.png"],
  },
  {
    id: 7,
    image: "housesImages/garni.png",
    night: true,
    people: "22",
    prace: "110,000Դ",
    title: "Գառնի",
    sliderImages: ["housesImages/garniS1.png", "housesImages/garniS2.png"],
  },
  {
    id: 8,
    image: "housesImages/ohanavan.png",
    night: false,
    people: "16",
    prace: "75,000Դ",
    title: "Օհանավան",
    sliderImages: [
      "housesImages/ohanavanS3.png",
      "housesImages/ohanavanS4.png",
    ],
  },
  {
    id: 9,
    image: "housesImages/mrgashen.png",
    night: true,
    people: "14",
    prace: "70,000Դ",
    title: "Մրգաշեն",
    sliderImages: [
      "housesImages/mrgashenS1.png",
      "housesImages/mrgashenS2.png",
    ],
  },
  {
    id: 10,
    image: "housesImages/hrazdan.png",
    night: false,
    people: "28",
    prace: "95,000Դ",
    title: "Հրազդան",
    sliderImages: ["housesImages/hrazdanS1.png", "housesImages/hrazdanS2.png"],
  },
  {
    id: 11,
    image: "housesImages/ohanavan1.png",
    night: true,
    people: "18",
    prace: "85,000Դ",
    title: "Օհանավան",
    sliderImages: [
      "housesImages/ohanavanS5.png",
      "housesImages/ohanavanS6.png",
    ],
  },
  {
    id: 12,
    image: "housesImages/caxkadzor.png",
    night: false,
    people: "24",
    prace: "90,000Դ",
    title: "Ծաղկաձոր",
    sliderImages: [
      "housesImages/caxkadzorS6.png",
      "housesImages/caxkadzorS7.png",
    ],
  },
  {
    id: 13,
    image: "housesImages/ohanavan2.png",
    night: true,
    people: "20",
    prace: "100,000Դ",
    title: "Օհանավան",
    sliderImages: [
      "housesImages/ohanavanS7.png",
      "housesImages/ohanavanS2.png",
    ],
  },
  {
    id: 14,
    image: "housesImages/erevan.png",
    night: false,
    people: "26",
    prace: "105,000Դ",
    title: "Երևան",
    sliderImages: ["housesImages/erevanS3.png", "housesImages/erevanS2.png"],
  },
];
